version: "3"
services:
  server:
    build:
      context: ../server/
      dockerfile: ../dev/server.Dockerfile
    restart: always
    volumes:
      - ../server:/go/src/github.com/CPCTF2022/Web_Generate_ORiginal_Memo/server
      - ../client:/go/src/github.com/CPCTF2022/Web_Generate_ORiginal_Memo/client
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: memo
      SESSION_SECRET: secret
      STATIC_ROOT: ../client/build
      APP_ADDR: :3000
    ports: 
      - 3000:3000
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: memo
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ../mysql/data:/var/lib/mysql

