name: Build Image

on:
  push:
    tags:
      - v*.*.*


jobs:
  push-image:
    name: Build Docker Image (master)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set REPO_NAME env
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set TAG env
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GAR
        uses: docker/login-action@v1
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_PROBLEM_REPOSITORY_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:${{env.TAG}}
            asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:latest
  push-config:
    name: Push Config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - config.yaml
          - docker-compose.yaml
    steps:
      - uses: actions/checkout@v3
      - name: Set REPO_NAME env
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_PROBLEM_REPOSITORY_ACCOUNT }}
      - name: Upload config.yml
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: ${{matrix.file}}
          destination: problem-config/${{env.REPO_NAME}}
          gzip: false